### ISSUE TITLE
Task: Responsive Sticky NavBar

### ISSUE THREAD

**Issue by Donny-C-1** [Donny-C-1/Shopxpress#5]
# Task Title

Task: Responsive Sticky NavBar

## Task Description

This task will make the nav-bar completely responsive. It will also make the nav-bar somewhat sticky. The nav-bar will remain static until the user has scrolled pass the header then it will slide down.

**Comment by DustyDogCodex** [comment]
Hi Donny,

If no one's working on this issue, I can try resolving it for you!
